---
- name: Installing homework1
  hosts: node1
  gather_facts: yes
  #vars_files:
  #       -  myvariables.yml
  tasks:
          - name: Installing httpd firewalld mariadb-server php php-mysqlnd
            yum:
                    name:
                            - "{{ item }}"
                    state: present
            register: user_tasks   
            
            loop:
                    - httpd
                    - firewalld
                    - mariadb-server
                    - php
                    - php-mysqlnd
            when: ansible_distribution == "CentOS"
          - name: Print what work it has done 
            debug:
                    msg: "{{ item }}  has been installed succesfully"
            loop:
                    - httpd
                    - firewalld
                    - mariadb-server
                    - php
                    - php-mysqlnd

          - name: Enabling and starting services of httpd firewalld & mariadb-server
            service:
                    name:
                            "{{ item }}"
                    enabled: true
                    state: restarted

            loop:
                    - httpd
                    - firewalld
                    - mariadb.service
           
                    
          - name: permits http
            firewalld:
                    service: http
                    permanent: true
                    state: enabled
                    immediate: yes
          
          - name: download a website
            get_url:
                    url: "https://www.phpclasses.org/browse/download/1/file/9052/name/test.php"
                    dest: /var/www/html/index.php
                    mode: 0644



